stages:
  - "publish"
  - "test"
  - "deploy"

variables:
   DOCKER_REGISTRY: 740657376690.dkr.ecr.us-east-1.amazonaws.com
   AWS_DEFAULT_REGION: us-east-1
   APP_NAME: nginx
   DOCKER_HOST: tcp://docker:2375

publish:
    stage: "publish"
    image: 
       name: amazon/aws-cli
       entrypoint: [""]
    services:
      - docker:dind
    before_script:
      - amazon-linux-extras install docker
      - aws --version
      - docker --version
    script:
      - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
      - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
      - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID

test:
    stage: "test"
    script: 
      - echo "valid"

deploy:
    stage: deploy
    script: 
        - sudo echo $CI_PIPELINE_IID > /home/ubuntu/variable.txt
        - export ver=$(cat /home/ubuntu/variable.txt)
        


   